### ISSUE TITLE
orthographic - is it my misunderstanding?

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/rtg-math#17]
I would like to transform screen coordinates (say, 800 x 600) to normalized device coordinates (-1.0 to 1.0)...  Much like `glm::ortho(0.0f, 800.0f, 600.0f, 0.0f, -1.0f, 1.0f)`,  I assumed I could simply
```lisp
(defparameter *projection* (rtg-math.projection:orthographic 800 600 -1.0 1.0) )
```
However, feeding in (800,600) results in:
```lisp
 (rtg-math.matrix4:*v *projection* (v4! 800 600 0.0 0.0))
#(2.0 2.0 0.0 0.0)
```
So it seems the range is 0.0 to 2.0 instead of -1.0 to 1.0 as I expected.  Am I incorrect?

**Comment by stacksmith** [comment]
rtg-math does some weird stuff to center width/height?

**Comment by cbaggers** [comment]
Good question. I'll have a look at the implementation. I probably copied it badly from somewhere and messed it up in the process

**Comment by cbaggers** [comment]
Finally fixed this. Sorry to all for the wait.
https://github.com/cbaggers/rtg-math/commit/dd656e7760720a29c6a1856b965c8cdbc39d1f08
