### ISSUE TITLE
Add rtg-math to quicklisp...

### ISSUE THREAD

**Issue by BradWBeer** [cbaggers/rtg-math#2]
I know it's still in flux and the API will likely change, but to keep clinch in quicklisp, all the dependencies need to be in quicklisp too. And I've moved everything to rtg-math. I've updated clinch to the latest version. If not, I'll need to wait to add clinch 0.5 to quicklisp. Presently I'm using an older branch.

**Comment by cbaggers** [comment]
https://github.com/quicklisp/quicklisp-projects/issues/1054 
:)
