### ISSUE TITLE
+pi+ fails with non-default *read-default-float-format*

### ISSUE THREAD

**Issue by scymtym** [cbaggers/rtg-math#4]
The definition `(defconstant +pi+ (the single-float 3.1415926535897932384626433832795))` (and maybe others) is incorrect if the value of `*read-default-float-format*` is not `single-float`. I suggest using [exponent markers](http://clhs.lisp.se/Body/26_glo_e.htm#exponent_marker), i.e. `3.141...f0`.

**Comment by cbaggers** [comment]
Hehe well that's embarrassing! Thanks for pointing that out. Will fix asap

**Comment by cbaggers** [comment]
forgot to close this. Done
